"use client";
import Link from "next/link";
import {useEffect,useRef} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {api,API,PortfolioBoard,ProjectSummary,ReplacementProgramRecord} from "@/lib/api";
import {PlatformReadiness} from "@/lib/bench";
import {ConfigWarning} from "@/components/ReadinessPanel";
type DeploymentStatus={database_reachable:boolean;schema_ready:boolean;bootstrap_required:boolean;alembic_version?:string|null;material_count?:number;reference_library_ready?:boolean};
type FlagshipDemoResult={status:string;project_id:string;program_id:string;project_name:string;program_name:string;is_demonstration_data:boolean};
type BootstrapResult={status:string;organisation_id:string;installed_count:number;skipped_count:number;deployment:DeploymentStatus};
function Spark({variant=0}:{variant?:number}){const p=["M2 24 10 19 18 21 27 11 36 15 44 8 53 12 62 2","M2 24 10 21 18 13 27 18 36 9 44 14 53 6 62 3","M2 21 10 23 18 16 27 18 36 12 44 14 53 8 62 4"];return <svg className="spark" viewBox="0 0 64 28"><path d={p[variant%3]}/></svg>}
function candidateDecision(row:PortfolioBoard["candidates"][number]){if(row.eligibility==="blocked")return "REJECT";if(row.gates_satisfied)return "ADVANCE";return "HOLD / TEST"}
export default function Dashboard(){
  const qc=useQueryClient();const booted=useRef(false);
  const deployment=useQuery({queryKey:["deployment-status"],queryFn:()=>api<DeploymentStatus>("/deployment/status"),retry:1});
  const bootstrap=useMutation({mutationFn:()=>api<BootstrapResult>("/deployment/bootstrap",{method:"POST"}),onSuccess:async()=>{await qc.invalidateQueries({queryKey:["deployment-status"]});await qc.invalidateQueries({queryKey:["platform-readiness"]});await qc.invalidateQueries({queryKey:["projects"]})}});
  useEffect(()=>{if(deployment.data?.bootstrap_required&&!booted.current){booted.current=true;bootstrap.mutate()}},[deployment.data?.bootstrap_required]);
  const ready=deployment.data?.database_reachable===true&&deployment.data?.bootstrap_required===false;
  const projects=useQuery({queryKey:["projects"],queryFn:()=>api<ProjectSummary[]>("/replacement-projects"),enabled:ready});
  const readiness=useQuery({queryKey:["platform-readiness"],queryFn:()=>api<PlatformReadiness>("/bench/readiness"),enabled:ready});
  const installLibrary=useMutation({mutationFn:()=>api<{installed_count:number}>("/bench/install-reference-library",{method:"POST",body:"{}"}),onSuccess:()=>{qc.invalidateQueries({queryKey:["platform-readiness"]});qc.invalidateQueries({queryKey:["deployment-status"]})}});
  const installFlagshipDemo=useMutation({mutationFn:()=>api<FlagshipDemoResult>("/bench/install-flagship-demo",{method:"POST",body:"{}"}),onSuccess:async r=>{await qc.invalidateQueries({queryKey:["projects"]});window.location.assign(`/projects/${r.project_id}/replacement`)}});
  const active=projects.data?.filter(p=>p.status==="active").length??0;const reqs=projects.data?.reduce((n,p)=>n+p.constraint_count,0)??0;const candidates=projects.data?.reduce((n,p)=>n+p.candidate_count,0)??0;const materials=readiness.data?.material_count??deployment.data?.material_count??0;
  const flagship=projects.data?.find(p=>p.name.toLowerCase().includes("high-temperature silicon replacement"));
  const program=useQuery({queryKey:["dashboard-program",flagship?.id],enabled:!!flagship?.id,queryFn:async()=>{const r=await api<ReplacementProgramRecord[]>(`/replacement-programs?project_id=${encodeURIComponent(flagship!.id)}`);return r.find(x=>x.is_demonstration_data)??r[0]??null}});
  const board=useQuery({queryKey:["dashboard-board",program.data?.id],enabled:!!program.data?.id,queryFn:()=>api<PortfolioBoard>(`/replacement-programs/${program.data!.id}/portfolio`)});
  return <>
    <div className="mission-titlebar"><div><div className="eyebrow">Mission Control</div><h1>Material Replacement Command Center</h1><p>Evaluate, test, and decide candidate materials through evidence-backed workflows.</p></div><div className="title-actions"><Link className="btn btn-secondary" href="/materials">Explore materials</Link><Link className="btn" href="/studies/new">+ New mission</Link></div></div>
    <ConfigWarning/>
    {(deployment.error||bootstrap.error)&&<div className="notice fail dashboard-alert"><strong>Workspace runtime needs attention.</strong><span>{(deployment.error as Error)?.message||(bootstrap.error as Error)?.message}</span><code>{API}</code></div>}
    {(deployment.isLoading||bootstrap.isPending)&&<div className="notice dashboard-alert"><strong>Preparing scientific workspace…</strong><span>Checking API, schema and reference data.</span></div>}
    <section className="kpi-grid"><article className="kpi-card blue"><span className="kpi-icon">↗</span><div><small>Active missions</small><strong>{active}</strong><span>{projects.data?.length??0} total studies</span></div><Spark/></article><article className="kpi-card violet"><span className="kpi-icon">△</span><div><small>Candidates under review</small><strong>{candidates}</strong><span>Across active missions</span></div><Spark variant={1}/></article><article className="kpi-card cyan"><span className="kpi-icon">◇</span><div><small>Formal requirements</small><strong>{reqs}</strong><span>Gates + objectives</span></div><Spark variant={2}/></article><article className="kpi-card green"><span className="kpi-icon">✓</span><div><small>Materials available</small><strong>{materials||"—"}</strong><span>{ready?"Database ready":"Checking workspace"}</span></div><Spark/></article></section>
    <section className="dashboard-main-grid"><div className="mission-control-card"><div className="panel-head"><div><span className="panel-kicker">Replacement programme</span><h2>{flagship?.name||"Flagship material replacement mission"}</h2></div>{flagship&&<Link href={`/projects/${flagship.id}/replacement`}>Open full mission →</Link>}</div><div className="mission-overview-grid"><div className="mission-brief"><span className="highlight-chip">FLAGSHIP DEMO</span><h3>Replace Silicon for High-Temperature Power Electronics</h3><div className="mission-conditions"><span>♨ <b>525 K</b></span><span>ϟ <b>3.3 kV</b></span></div><p>Find a replacement while preserving blocking requirements and keeping evidence gaps explicit.</p><div className="mission-owner"><span className="avatar mini">TL</span><span><small>Decision method</small><b>Evidence-first replacement OS</b></span></div></div><div className="candidate-strip"><div className="candidate-mini incumbent"><span className="crystal-icon">Si</span><small>INCUMBENT</small><strong>Silicon</strong><em>Reference material</em></div>{(board.data?.candidates??[]).slice(0,3).map((c,i)=>{const d=candidateDecision(c);return <Link href={`/projects/${flagship!.id}/replacement`} className={`candidate-mini candidate-${i}`} key={c.candidate_id}><span className="crystal-icon">{String.fromCharCode(65+i)}</span><small>CANDIDATE {i+1}</small><strong>{c.display_name}</strong><em className={`decision-${d.toLowerCase().replace(/[^a-z]+/g,"-")}`}>{d}</em></Link>})}{!board.data&&["Candidate A","Candidate B","Candidate C"].map((n,i)=><div className={`candidate-mini candidate-${i}`} key={n}><span className="crystal-icon">{String.fromCharCode(65+i)}</span><small>DEMO PATH</small><strong>{n}</strong><em>Load flagship data</em></div>)}</div></div><div className="decision-funnel">{[["Define","Mission & context"],["Screen","Shortlist candidates"],["Test","Generate evidence"],["Decide","Evaluate gates"],["Next Action","Execute & learn"]].map(([a,b],i)=><div key={a} className={i===3?"active":""}><span>{i+1}</span><b>{a}</b><small>{b}</small>{i<4&&<i>→</i>}</div>)}</div></div>
    <aside className="flagship-story-card"><div className="panel-head"><div><span className="panel-kicker">Decision story</span><h2>What TinkerLab decides</h2></div></div>{(board.data?.candidates??[]).slice(0,3).map((c,i)=>{const d=candidateDecision(c);return <div className={`story-row story-${d.toLowerCase().replace(/[^a-z]+/g,"-")}`} key={c.candidate_id}><span className="story-index">{String.fromCharCode(65+i)}</span><div><small>CANDIDATE {String.fromCharCode(65+i)}</small><strong>{c.display_name}</strong><p>{d==="ADVANCE"?"Blocking requirements satisfied on current evidence.":d==="REJECT"?"Definitive blocking evidence prevents advancement.":"More evidence is required before a defensible decision."}</p></div><b>{d}</b></div>})}{!board.data&&<div className="story-empty"><p>Load the flagship programme to populate ADVANCE / REJECT / HOLD from the decision engine.</p>{flagship?<Link className="btn" href={`/projects/${flagship.id}/replacement`}>Open demo story</Link>:<button className="btn" disabled={!ready||installFlagshipDemo.isPending} onClick={()=>installFlagshipDemo.mutate()}>{installFlagshipDemo.isPending?"Installing…":"Load flagship demo"}</button>}</div>}{flagship&&<Link className="text-link" href={`/projects/${flagship.id}/replacement`}>View evidence-backed story →</Link>}</aside></section>
    <section className="dashboard-lower-grid"><div className="health-panel"><div className="panel-head"><div><span className="panel-kicker">Programme health</span><h2>Scientific workflow readiness</h2></div><span className={`runtime-state ${ready?"ready":"checking"}`}><i/>{ready?"READY":"CHECKING"}</span></div><div className="health-chart"><div className="grid-lines"/><svg viewBox="0 0 620 170" preserveAspectRatio="none"><defs><linearGradient id="healthFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2d8cff" stopOpacity=".34"/><stop offset="1" stopColor="#2d8cff" stopOpacity="0"/></linearGradient></defs><path className="fill" d="M0 133 L48 121 L96 125 L144 96 L192 105 L240 73 L288 86 L336 58 L384 66 L432 42 L480 49 L528 31 L580 39 L620 27 L620 170 L0 170Z"/><path d="M0 133 L48 121 L96 125 L144 96 L192 105 L240 73 L288 86 L336 58 L384 66 L432 42 L480 49 L528 31 L580 39 L620 27"/></svg><div className="chart-axis"><span>Define</span><span>Screen</span><span>Test</span><span>Decide</span><span>Act</span></div></div></div><div className="coverage-panel"><div className="panel-head"><div><span className="panel-kicker">Workspace coverage</span><h2>Operational foundation</h2></div></div>{[["Database",deployment.data?.database_reachable?100:0],["Schema",deployment.data?.schema_ready?100:0],["Reference library",deployment.data?.reference_library_ready?100:Math.min(95,materials*3)],["Mission definitions",projects.data?.length?Math.min(100,45+projects.data.length*12):15]].map(([label,v],i)=><div className="coverage-row" key={String(label)}><span><i className={`coverage-dot d${i}`}/>{label}</span><div><b style={{width:`${Number(v)}%`}}/></div><strong>{Number(v)}%</strong></div>)}{ready&&materials<5&&<button className="btn btn-secondary btn-sm" disabled={installLibrary.isPending} onClick={()=>installLibrary.mutate()}>{installLibrary.isPending?"Installing…":"Install reference library"}</button>}</div></section>
    <section className="action-panel"><div className="panel-head"><div><span className="panel-kicker">Active work</span><h2>Replacement missions</h2></div><Link href="/studies/new">Create mission →</Link></div><div className="action-table"><div className="action-table-head"><span>Mission</span><span>Baseline</span><span>Requirements</span><span>Candidates</span><span>Status</span></div>{(projects.data??[]).slice(0,6).map(p=><Link href={`/projects/${p.id}`} className="action-table-row" key={p.id}><span><b>{p.name}</b><small>{p.description||p.replacement_reasons.join(", ")}</small></span><span>{p.baseline_material.display_name}</span><span>{p.constraint_count}</span><span>{p.candidate_count}</span><span><em className="status-live"><i/>{p.status}</em></span></Link>)}{projects.isLoading&&<div className="empty">Loading missions…</div>}{projects.data?.length===0&&<div className="story-empty"><p>No replacement missions yet.</p><button className="btn" onClick={()=>installFlagshipDemo.mutate()} disabled={!ready||installFlagshipDemo.isPending}>Load flagship mission</button></div>}</div></section>
  </>;
}
