"use client";
import { use } from "react";
import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, MaterialDetailV2 } from "@/lib/api";

type Selection={property_key:string;selected?:{observation_id:string;numeric_value?:number;boolean_value?:boolean;unit?:string;canonical_value?:number;canonical_unit?:string;applicability:string;evidence_type:string;evidence_title:string;curator_preferred:boolean};rationale:string[];alternatives:Array<Record<string,unknown>>;excluded:Array<Record<string,unknown>>;conflict:boolean;scientific_conflict:boolean;unknown_reason?:string};
type Conflict={property_key:string;policy:string;observation_ids:string[];conditions:Record<string,unknown>;reasons:string[];resolution_state:string};
const conditionText=(o:MaterialDetailV2["observations"][number])=>{const c=o.condition_set;if(!c)return "Conditions not reported";const parts=[];if(c.temperature_value!==undefined)parts.push(`${c.temperature_value} ${c.temperature_unit}`);if(c.pressure_value!==undefined)parts.push(`${c.pressure_value} ${c.pressure_unit}`);if(c.humidity_percent!==undefined)parts.push(`${c.humidity_percent}% RH`);if(c.material_state)parts.push(c.material_state);return parts.join(" · ")||"No common conditions reported"};
export default function MaterialPassport({params}:{params:Promise<{id:string}>}){
  const {id}=use(params); const qc=useQueryClient();
  const q=useQuery({queryKey:["material",id],queryFn:()=>api<MaterialDetailV2>(`/materials/${id}`)});
  const selections=useQuery({queryKey:["selection-summary",id],queryFn:()=>api<Selection[]>(`/material-selection-summary/${id}`)});
  const conflicts=useQuery({queryKey:["conflicts",id],queryFn:()=>api<Conflict[]>(`/materials/${id}/conflicts`)});
  const prefer=useMutation({mutationFn:({observationId,rationale}:{observationId:string;rationale:string})=>api(`/observations/${observationId}/curator-preference?preferred=true&rationale=${encodeURIComponent(rationale)}`,{method:"POST"}),onSuccess:()=>{qc.invalidateQueries({queryKey:["material",id]});qc.invalidateQueries({queryKey:["selection-summary",id]});qc.invalidateQueries({queryKey:["conflicts",id]});}});
  if(q.isLoading)return <div className="empty">Loading material passport…</div>;
  if(q.error||!q.data)return <div className="empty">Material unavailable: {(q.error as Error)?.message}</div>;
  const m=q.data; const evidence=[...new Map(m.observations.map(o=>[o.evidence.id,o.evidence])).values()];
  return <>
    <div className="topline"><div><div className="eyebrow">Material passport · evidence graph</div><h1>{m.display_name}</h1><div className="muted">{m.canonical_name} · {m.material_family} · {m.visibility}</div></div><div style={{display:"flex",gap:8,alignItems:"center"}}><Link className="btn" href={`/materials/${m.id}/add-data`}>Add property data</Link><Link className="btn btn-secondary" href={`/studies/new?baseline=${m.id}`}>Start a study</Link><span className="badge">{m.source_type}</span></div></div>
    {m.is_seed_data&&<div className="notice" style={{marginBottom:18}}>Demonstration material. Every seeded value is synthetic workflow data and is not an experimental, supplier, literature, or computational claim.</div>}
    <div className="grid grid-2" style={{marginBottom:18}}>
      <div className="card card-pad"><h2>Identity</h2><p>{m.description}</p><div className="kicker">Identifiers & aliases</div><div style={{display:"flex",flexWrap:"wrap",gap:7,marginTop:8}}>{m.identifiers.map(i=><span className="badge" key={i.id}>{i.namespace}: {i.value}{i.is_primary?" · primary":""}</span>)}{m.identifiers.length===0&&<span className="muted">None reported</span>}</div><div className="kicker" style={{marginTop:18}}>Legacy composition summary</div><p>{m.composition_summary??"Not provided"}</p></div>
      <div className="card card-pad"><h2>Evidence posture</h2><p className="muted">{m.observations.length} observations · {evidence.length} evidence record(s) · {conflicts.data?.length??0} detected conflict(s)</p><p>Selected observations are chosen by an explicit condition/evidence policy. Alternatives remain visible and are never averaged silently.</p></div>
    </div>
    <div className="card" style={{marginBottom:18}}><div className="card-pad"><h2>Structured composition / formulation</h2></div><div className="table-wrap"><table><thead><tr><th>Component</th><th>Role</th><th>Amount</th><th>Basis</th><th>Evidence</th></tr></thead><tbody>{m.components.map(c=><tr key={c.id}><td><strong>{c.is_redacted?(c.redaction_label??"Redacted component"):c.component_name}</strong>{c.is_redacted&&<div className="muted">customer-private identifier</div>}</td><td>{c.component_role??"—"}</td><td>{c.is_redacted?"REDACTED":c.amount_value!==undefined?`${c.amount_value} ${c.amount_unit??""}`:c.amount_lower!==undefined?`${c.amount_lower}–${c.amount_upper} ${c.amount_unit??""}`:"present"}</td><td>{c.amount_basis}</td><td>{c.evidence_id?<code>{c.evidence_id.slice(0,8)}…</code>:"—"}</td></tr>)}{m.components.length===0&&<tr><td colSpan={5}><div className="empty">No structured composition has been reported.</div></td></tr>}</tbody></table></div></div>
    <div className="card" style={{marginBottom:18}}><div className="card-pad"><h2>Processing / material state</h2></div><div className="table-wrap"><table><thead><tr><th>Sequence</th><th>State</th><th>Process</th><th>Parameters</th></tr></thead><tbody>{m.process_states.map(s=><tr key={s.id}><td>{s.sequence}</td><td>{s.state_label}</td><td>{s.process_name??"—"}</td><td><code>{Object.keys(s.parameters).length?JSON.stringify(s.parameters):"—"}</code></td></tr>)}{m.process_states.length===0&&<tr><td colSpan={4}><div className="empty">No processing state reported.</div></td></tr>}</tbody></table></div></div>
    <div className="card" style={{marginBottom:18}}><div className="card-pad"><h2>Selected property observations</h2><p className="muted">Default passport selection uses no project-specific condition context. Project comparisons can select a different observation when their conditions require it.</p></div><div className="table-wrap"><table><thead><tr><th>Property</th><th>Selected value</th><th>Applicability</th><th>Evidence</th><th>Alternatives</th><th>Conflict</th></tr></thead><tbody>{selections.data?.map(s=><tr key={s.property_key}><td><strong>{s.property_key}</strong></td><td>{!s.selected?"UNKNOWN":s.selected.boolean_value!==undefined?String(s.selected.boolean_value):`${s.selected.numeric_value} ${s.selected.unit??""}`}</td><td>{s.selected?<span className="badge">{s.selected.applicability}</span>:"—"}</td><td>{s.selected?<Link href={`/observations/${s.selected.observation_id}`}>{s.selected.evidence_title}</Link>:"—"}</td><td>{s.alternatives.length}</td><td>{s.scientific_conflict?<span className="badge fail">Review conflict</span>:s.conflict?<span className="badge unknown">Selection tie</span>:<span className="badge pass">No conflict</span>}</td></tr>)}</tbody></table></div></div>
    <div className="card" style={{marginBottom:18}}><div className="card-pad"><h2>All observations</h2></div><div className="table-wrap"><table><thead><tr><th>Property</th><th>Reported value</th><th>Conditions</th><th>Status</th><th>Uncertainty</th><th>Evidence</th></tr></thead><tbody>{m.observations.map(o=><tr key={o.id}><td><Link href={`/observations/${o.id}`}><strong>{o.property_definition.display_name}</strong></Link><div className="muted">{o.property_definition.key}</div></td><td>{o.value_type==="boolean"?String(o.boolean_value):`${o.numeric_value} ${o.unit??""}`}</td><td>{conditionText(o)}</td><td><span className={`badge ${o.status==="active"?"pass":"unknown"}`}>{o.status}</span>{o.curator_preferred&&<div><span className="badge">curator preferred</span></div>}</td><td>{o.uncertainty??o.uncertainty_stddev??"—"}</td><td><span className="badge">{o.evidence.evidence_type}</span><div>{o.evidence.title}</div></td></tr>)}</tbody></table></div></div>
    {conflicts.data&&conflicts.data.length>0&&<div className="card" style={{marginBottom:18}}><div className="card-pad"><h2>Conflict review</h2><p className="muted">A preference changes selection policy; it does not delete or rewrite the other observation.</p></div>{conflicts.data.map(c=><div key={c.property_key} className="card-pad" style={{borderTop:"1px solid var(--line)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><strong>{c.property_key}</strong><div className="muted">Policy: {c.policy} · {c.resolution_state}</div></div><span className="badge fail">{c.observation_ids.length} observations</span></div><p>{c.reasons.join("; ")}</p><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{c.observation_ids.map(oid=><button className="btn btn-secondary" key={oid} disabled={prefer.isPending} onClick={()=>prefer.mutate({observationId:oid,rationale:`Reviewed ${c.property_key} conflict in Material Passport`})}>Prefer {oid.slice(0,8)}…</button>)}</div></div>)}</div>}
    <div className="card"><div className="card-pad"><h2>Evidence records</h2></div>{evidence.map(e=><div key={e.id} className="card-pad" style={{borderTop:"1px solid var(--line)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><strong>{e.title}</strong><span className="badge">{e.evidence_type}</span></div><p className="muted">{e.description}</p><div className="grid grid-2"><div><span className="kicker">Method</span><p>{e.method??"Not specified"}</p></div><div><span className="kicker">Provider / status</span><p>{e.provider?.display_name??"Direct evidence"} · {e.status}</p></div></div></div>)}</div>
  </>;
}
