"use client";
import {use, useState} from "react";
import Link from "next/link";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {api,CampaignPreview,OptimizationDecision,ParetoFront,VirtualCampaignDetail,VirtualCampaignRunResult,VirtualEvaluationPage} from "@/lib/api";
import {VirtualEvaluationWarning} from "@/components/VirtualEvaluationWarning";
import {ParetoScatter} from "@/components/ParetoScatter";

const feasibilityClass=(x:string)=>x==="robustly_feasible"?"pass":x==="robustly_infeasible"?"fail":"unknown";
export default function VirtualCampaignPage({params}:{params:Promise<{id:string}>}){
  const {id}=use(params);const qc=useQueryClient();const [preview,setPreview]=useState<CampaignPreview|null>(null);const [selectedIteration,setSelectedIteration]=useState<string>("");
  const detail=useQuery({queryKey:["virtual-campaign",id],queryFn:()=>api<VirtualCampaignDetail>(`/virtual-campaigns/${id}`)});
  const latest=selectedIteration||detail.data?.iterations.at(-1)?.id||"";
  const evaluations=useQuery({queryKey:["virtual-evaluations",latest],queryFn:()=>api<VirtualEvaluationPage>(`/campaign-iterations/${latest}/evaluations?offset=0&limit=200`),enabled:!!latest});
  const fronts=useQuery({queryKey:["virtual-pareto",latest],queryFn:()=>api<ParetoFront[]>(`/campaign-iterations/${latest}/pareto`),enabled:!!latest});
  const decisions=useQuery({queryKey:["virtual-decisions",latest],queryFn:()=>api<OptimizationDecision[]>(`/campaign-iterations/${latest}/decisions`),enabled:!!latest});
  const previewRun=useMutation({mutationFn:()=>api<CampaignPreview>(`/virtual-campaigns/${id}/preview`,{method:"POST"}),onSuccess:setPreview});
  const execute=useMutation({mutationFn:()=>api<VirtualCampaignRunResult>(`/virtual-campaigns/${id}/run`,{method:"POST",body:JSON.stringify({})}),onSuccess:async()=>{setPreview(null);await qc.invalidateQueries({queryKey:["virtual-campaign",id]});}});
  const objectiveKeys=detail.data?.objectives.map(o=>o.property_key)??[];
  const twoD=objectiveKeys.length===2?objectiveKeys:null;
  const evals=evaluations.data?.items??[];
  if(detail.isLoading)return <div className="empty">Loading virtual campaign…</div>;
  if(detail.error||!detail.data)return <div className="empty">Campaign unavailable: {(detail.error as Error)?.message}</div>;
  const c=detail.data.campaign; const canRun=!(["completed","cancelled","failed"].includes(c.status));
  return <div className="grid">
    <div className="topline"><div><div className="eyebrow">Virtual Experiment Campaign · Phase 5</div><h1>{c.name}</h1><div className="muted">{c.description}</div></div><div style={{display:"flex",gap:8}}><Link className="btn btn-secondary" href={`/projects/${c.project_id}/virtual-lab`}>Virtual Lab</Link><Link className="btn btn-secondary" href="/simulation">Physics assessment</Link><Link className="btn btn-secondary" href={`/projects/${c.project_id}`}>Project</Link></div></div>
    <VirtualEvaluationWarning/>
    <div className="grid grid-3"><div className="card stat"><span className="kicker">Status</span><strong>{c.status}</strong><div className="muted">{c.stop_reason??"No stop signal"}</div></div><div className="card stat"><span className="kicker">Policy</span><strong>{c.policy_key}</strong><div className="muted">v{c.policy_version} · seed {c.random_seed}</div></div><div className="card stat"><span className="kicker">Budget</span><strong>{c.max_iterations} iterations</strong><div className="muted">{c.max_total_new_candidates} total new hypotheses</div></div></div>
    <div className="card card-pad"><div className="grid grid-2"><div><span className="kicker">Replacement specification</span><p><code>{c.replacement_specification_checksum}</code></p><span className="kicker">Search-space snapshot</span><p>v{c.search_space_version} · <code>{c.search_space_checksum}</code></p></div><div><span className="kicker">Campaign configuration</span><p><code>{c.configuration_checksum}</code></p><span className="kicker">Result checksum</span><p><code>{c.result_checksum??"Not completed"}</code></p></div></div></div>
    <div className="card"><div className="card-pad"><div className="topline"><div><div className="eyebrow">Pinned objectives</div><h2>Explicit multi-objective trade-offs</h2></div><div style={{display:"flex",gap:8}}><button className="btn btn-secondary" disabled={previewRun.isPending} onClick={()=>previewRun.mutate()}>Preview only</button><button className="btn" disabled={!canRun||!preview?.valid||execute.isPending} onClick={()=>execute.mutate()}>Run bounded campaign</button></div></div>{preview&&<div className={`notice ${preview.valid?"":"fail"}`} data-testid="campaign-preview"><strong>{preview.valid?"Preview valid":"Preview blocked"}</strong><div>{preview.candidate_pool_size} candidates · {preview.estimated_prediction_runs} expected prediction run(s) · estimated mutation cardinality {preview.estimated_mutation_cardinality}</div><div className="muted">Preview creates no iterations, predictions, or hypotheses.</div>{preview.validation_issues.map(i=><div key={`${i.code}-${i.path}`}>{i.severity.toUpperCase()} · {i.code}: {i.message}</div>)}</div>}</div><div className="table-wrap"><table><thead><tr><th>Property</th><th>Direction</th><th>Priority</th><th>Model version</th><th>Evaluation mode</th></tr></thead><tbody>{detail.data.objectives.map(o=><tr key={o.id}><td><strong>{o.property_key}</strong></td><td>{o.direction}</td><td>{o.priority}</td><td><code>{o.model_version_id.slice(0,14)}…</code></td><td>{o.evaluation_mode}</td></tr>)}</tbody></table></div></div>
    <div className="card"><div className="card-pad"><div className="topline"><div><div className="eyebrow">Iterations</div><h2>Every decision remains inspectable</h2></div>{detail.data.iterations.length>0&&<select className="select" style={{width:"auto"}} value={latest} onChange={e=>setSelectedIteration(e.target.value)}>{detail.data.iterations.map(i=><option key={i.id} value={i.id}>Iteration {i.iteration_number}</option>)}</select>}</div></div><div className="table-wrap"><table><thead><tr><th>Iteration</th><th>Evaluated</th><th>Feasibility</th><th>Pareto front</th><th>Parents</th><th>Children / duplicates</th><th>Stop</th></tr></thead><tbody>{detail.data.iterations.map(i=><tr key={i.id}><td><strong>#{i.iteration_number}</strong><div className="muted"><code>{i.decision_checksum?.slice(0,12)??"—"}…</code></div></td><td>{i.evaluated_candidate_count}</td><td><span className="badge pass">{i.feasible_count} feasible</span> <span className="badge unknown">{i.uncertain_count} uncertain</span> <span className="badge fail">{i.infeasible_count} infeasible</span></td><td>{i.pareto_front_count}</td><td>{i.selected_for_exploration_count}</td><td>{i.new_candidate_count} / {i.duplicate_count}</td><td>{i.stop_signal?<span className="badge unknown">{i.stop_reason}</span>:"continue"}</td></tr>)}</tbody></table></div></div>
    {latest&&<><div className="card card-pad"><div className="eyebrow">Pareto Explorer</div><h2>Conservative objective trade-offs</h2><p className="muted">Pareto ranking uses uncertainty-aware conservative values. Point estimates and intervals remain visible; this is not a global optimum claim.</p>{twoD?<ParetoScatter evaluations={evals} xKey={twoD[0]} yKey={twoD[1]}/>:<div className="empty">Use the evaluation table for campaigns with other than two objectives.</div>}<p className="muted">Front snapshots: {fronts.data?.map(f=>`P${f.front_number}=${f.ordered_candidate_ids.length}`).join(" · ")??"…"}</p></div>
    <div className="card"><div className="card-pad"><h2>Candidate evaluations</h2><p className="muted">No opaque aggregate score. Each row retains hard-constraint posture, objective intervals, Pareto rank and parent-selection rationale.</p></div><div className="table-wrap"><table><thead><tr><th>Candidate</th><th>Feasibility</th><th>Hard constraints</th><th>Objectives</th><th>Pareto</th><th>Decision</th></tr></thead><tbody>{evals.map(e=><tr key={e.id}><td>{e.hypothesis_id?<Link href={`/candidate-hypotheses/${e.hypothesis_id}`}><strong>Hypothesis {e.hypothesis_id.slice(0,8)}…</strong></Link>:<code>{e.candidate_id.slice(0,12)}…</code>}<div className="muted">{e.scientific_origin}</div></td><td><span className={`badge ${feasibilityClass(e.feasibility_class)}`}>{e.feasibility_class}</span></td><td>PASS {e.hard_pass_count} · FAIL {e.hard_fail_count} · UNKNOWN {e.hard_unknown_count}</td><td>{Object.entries(e.objective_vector).map(([k,v])=>{const i=e.objective_intervals[k];return <div key={k}><strong>{k}</strong> {v.point===undefined||v.point===null?"UNKNOWN":`${Number(v.point).toFixed(2)} ${v.unit??""}`}<div className="muted">{i?.lower!==undefined&&i?.upper!==undefined?`interval ${Number(i.lower).toFixed(2)}–${Number(i.upper).toFixed(2)} · conservative ${v.conservative_value}`:"incomplete"}</div></div>})}</td><td>{e.pareto_rank?`P${e.pareto_rank}`:"incomplete"}<div className="muted">dominance {e.dominance_count}</div></td><td>{e.selected_as_parent?<span className="badge pass">Selected parent</span>:<span className="badge">Evaluated</span>}<div className="muted">{e.rationale}</div></td></tr>)}</tbody></table></div></div>
    <div className="card"><div className="card-pad"><h2>Decision ledger</h2><p className="muted">Policy/version, input checksum, metrics and rationale are persisted for every selection, rejection, duplicate and mutation.</p></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Decision</th><th>Candidate</th><th>Rationale</th><th>Input checksum</th></tr></thead><tbody>{decisions.data?.map(d=><tr key={d.id}><td>{d.sequence}</td><td><span className="badge">{d.decision_type}</span></td><td>{d.hypothesis_id?<Link href={`/candidate-hypotheses/${d.hypothesis_id}`}>{d.hypothesis_id.slice(0,10)}…</Link>:d.candidate_id?.slice(0,10)??"—"}</td><td>{d.rationale}</td><td><code>{d.input_checksum.slice(0,14)}…</code></td></tr>)}</tbody></table></div></div></>}
  </div>;
}
