"use client";
import { use } from "react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { api, CandidateHypothesis, CandidateLineage, Evaluation, GenerationRun, PredictionHistoryItem } from "@/lib/api";
import { HypothesisWarning } from "@/components/HypothesisWarning";
import { GenerationRunSummary } from "@/components/GenerationRunSummary";
import { StatusBadge } from "@/components/StatusBadge";
import { PredictionInterval } from "@/components/PredictionInterval";
import { PredictionOriginBadge } from "@/components/PredictionOriginBadge";

export default function CandidateHypothesisPage({params}:{params:Promise<{id:string}>}) {
  const {id}=use(params);
  const hypothesis=useQuery({queryKey:["hypothesis",id],queryFn:()=>api<CandidateHypothesis>(`/candidate-hypotheses/${id}`)});
  const lineage=useQuery({queryKey:["hypothesis-lineage",id],queryFn:()=>api<CandidateLineage[]>(`/candidate-hypotheses/${id}/lineage`),enabled:!!hypothesis.data});
  const predictions=useQuery({queryKey:["hypothesis-predictions",id],queryFn:()=>api<PredictionHistoryItem[]>(`/candidate-hypotheses/${id}/predictions`),enabled:!!hypothesis.data});
  const selectedPredictionRun=predictions.data?.[0]?.prediction_run_id;
  const comparison=useQuery({queryKey:["comparison-hypothesis",hypothesis.data?.project_id,selectedPredictionRun],queryFn:()=>api<Evaluation[]>(`/replacement-projects/${hypothesis.data!.project_id}/comparison?include_hypotheses=true${selectedPredictionRun?`&prediction_run_id=${selectedPredictionRun}`:""}`),enabled:!!hypothesis.data});
  const run=useQuery({queryKey:["generation-run",hypothesis.data?.generation_run_id],queryFn:()=>api<GenerationRun>(`/generation-runs/${hypothesis.data!.generation_run_id}`),enabled:!!hypothesis.data?.generation_run_id});
  if(hypothesis.isLoading) return <div className="empty">Loading hypothesis…</div>;
  if(hypothesis.error||!hypothesis.data) return <div className="empty">Hypothesis unavailable: {(hypothesis.error as Error)?.message}</div>;
  const h=hypothesis.data; const ev=comparison.data?.find(x=>x.hypothesis_id===h.id);
  return <div className="grid">
    <div className="topline"><div><div className="eyebrow">Candidate hypothesis</div><h1>{h.display_label}</h1><div className="muted">{h.material_family} · {h.generator_strategy_key} v{h.generator_strategy_version}</div></div><div style={{display:"flex",gap:8}}><Link className="btn" href={`/projects/${h.project_id}/prediction-lab`}>Prediction Lab</Link><Link className="btn btn-secondary" href={`/projects/${h.project_id}/candidate-lab`}>Candidate Lab</Link><span className="badge">{h.status}</span></div></div>
    <HypothesisWarning/>
    <div className="grid grid-2"><div className="card card-pad"><h2>Identity & structural posture</h2><p><span className="kicker">Structural validity</span><br/><StatusBadge status={h.structural_validity==="valid"?"PASS":"FAIL"}/> {h.structural_validity}</p>{h.rejection_reason&&<p className="muted">Rejection: {h.rejection_reason}</p>}<span className="kicker">Deterministic fingerprint</span><p><code>{h.deterministic_fingerprint}</code></p><span className="kicker">Fingerprint algorithm</span><p>{h.fingerprint_version}</p></div><div className="card card-pad"><h2>Scientific value posture</h2><p><strong>{ev?.evidence_posture ?? "UNKNOWN"}</strong></p><p className="muted">Structural validity is not a performance estimate. Baseline observations are never copied to this hypothesis.</p><div className="notice">{predictions.data?.length?`${predictions.data.length} explicit model prediction record(s) exist. They remain separate from evidence and carry applicability + uncertainty.`:"No model prediction exists for this hypothesis; unsupported properties remain UNKNOWN."}</div></div></div>

    <div className="card"><div className="card-pad"><h2>Predictions</h2><p className="muted">MODEL PREDICTION records are not measurements, simulations, or experimental validation.</p></div>{predictions.data?.length?<div className="table-wrap"><table><thead><tr><th>Origin</th><th>Prediction</th><th>Applicability</th><th>Status</th><th>Provenance</th></tr></thead><tbody>{predictions.data.map(p=><tr key={p.id}><td><PredictionOriginBadge origin="model_prediction"/></td><td><PredictionInterval point={p.numeric_point_estimate} lower={p.uncertainty_lower} upper={p.uncertainty_upper} unit={p.output_unit}/></td><td><span className="badge">{p.applicability_status}</span></td><td>{p.status}</td><td><Link href={`/predictions/${p.id}`}>Inspect model result</Link></td></tr>)}</tbody></table></div>:<div className="empty">UNKNOWN — no model-backed prediction has been created.</div>}</div>
    <div className="card"><div className="card-pad"><h2>Concrete proposed composition</h2><p className="muted">This is a proposal representation, not a synthesis procedure.</p></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Component</th><th>Role</th><th>Amount</th><th>Origin</th></tr></thead><tbody>{h.components.sort((a,b)=>a.sequence-b.sequence).map(c=><tr key={c.id}><td>{c.sequence+1}</td><td><strong>{c.display_name}</strong><div className="muted"><code>{c.component_key}</code></div></td><td>{c.role??"—"}</td><td>{c.amount===undefined||c.amount===null?"redacted/unspecified":`${c.amount} ${c.unit??""} ${c.basis??""}`}</td><td>{c.substitution_rule_id?`Substitution rule ${c.substitution_rule_id.slice(0,8)}…`:c.source_baseline_component_id?"Baseline component":"Manual/concrete input"}</td></tr>)}</tbody></table></div></div>
    <div className="card"><div className="card-pad"><h2>Proposed process-state parameters</h2><p className="muted">Data-level bounded variables only. No executable or hazardous process protocol is produced.</p></div>{h.process_parameters.length?<div className="table-wrap"><table><thead><tr><th>State</th><th>Parameter</th><th>Value</th></tr></thead><tbody>{h.process_parameters.map(p=><tr key={p.id}><td>{p.process_label}</td><td><code>{p.parameter_key}</code></td><td>{p.value} {p.unit}</td></tr>)}</tbody></table></div>:<div className="empty">No process parameter changes in this hypothesis.</div>}</div>
    <div className="card"><div className="card-pad"><h2>Diff from baseline / change records</h2></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Change</th><th>Target</th><th>Before</th><th>After</th><th>Rationale</th></tr></thead><tbody>{h.changes.sort((a,b)=>a.sequence-b.sequence).map(c=><tr key={c.id}><td>{c.sequence+1}</td><td>{c.change_type}</td><td><code>{c.target_path}</code></td><td><pre className="json" style={{maxWidth:260}}>{JSON.stringify(c.before_value,null,2)}</pre></td><td><pre className="json" style={{maxWidth:260}}>{JSON.stringify(c.after_value,null,2)}</pre></td><td>{c.rationale}</td></tr>)}</tbody></table></div></div>
    <div className="card"><div className="card-pad"><h2>Lineage</h2></div>{lineage.data?.length?<div className="table-wrap"><table><thead><tr><th>#</th><th>Relationship</th><th>Parent</th><th>Run</th><th>Rationale</th></tr></thead><tbody>{lineage.data.map(e=><tr key={e.id}><td>{e.sequence+1}</td><td>{e.relationship_type}</td><td>{e.parent_material_id?`Material ${e.parent_material_id.slice(0,8)}…`:e.parent_hypothesis_id?`Hypothesis ${e.parent_hypothesis_id.slice(0,8)}…`:e.parent_candidate_id?`Candidate ${e.parent_candidate_id.slice(0,8)}…`:"—"}</td><td>{e.generation_run_id?<Link href={`/generation-runs/${e.generation_run_id}`}>Open run</Link>:"Manual"}</td><td>{e.rationale}</td></tr>)}</tbody></table></div>:<div className="empty">No lineage edge found.</div>}</div>
    <div className="card"><div className="card-pad"><h2>Project constraints</h2><p className="muted">Known evidence is used first. The latest explicit prediction run may fill only missing evidence; interval-crossing predictions remain UNKNOWN.</p></div>{ev?<div className="table-wrap"><table><thead><tr><th>Property</th><th>Status</th><th>Observed/predicted</th><th>Reason</th></tr></thead><tbody>{ev.constraints.map((c,i)=><tr key={`${c.property_key}-${i}`}><td>{c.property_key}</td><td><StatusBadge status={c.status}/></td><td>—</td><td>{c.unknown_reason??"No independent evidence/prediction exists for this hypothesis."}</td></tr>)}</tbody></table></div>:<div className="empty">Loading constraint posture…</div>}</div>
    {run.data&&<GenerationRunSummary run={run.data}/>} 
  </div>;
}
