"""Phase 9 experimental design and validation OS

Revision ID: 0009_phase9
Revises: 0008_phase8
Create Date: 2026-08-13

Forward-only. Migrations 0001-0008 are NOT edited.

Autogenerated and then filtered, as for 0008: statements that autogenerate proposed against
Phase 1-8 tables were discarded rather than applied, since they reflect pre-existing schema drift
and applying them here would silently alter earlier phases' schema.

Downgrade removes only Phase-9 experiment tables. No observation, prediction, simulation, campaign,
industrial or reasoning record is created, altered or deleted by either direction.
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0009_phase9"
down_revision = "0008_phase8"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('experiment_protocols',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('property_definition_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['property_definition_id'], ['material_property_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'key', name='uq_experiment_protocol_scope_key')
    )
    op.create_index(op.f('ix_experiment_protocols_key'), 'experiment_protocols', ['key'], unique=False)
    op.create_index(op.f('ix_experiment_protocols_organisation_id'), 'experiment_protocols', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_experiment_protocols_property_definition_id'), 'experiment_protocols', ['property_definition_id'], unique=False)
    op.create_index(op.f('ix_experiment_protocols_status'), 'experiment_protocols', ['status'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('instrument_type', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('asset_reference', sa.String(length=160), nullable=True),
    sa.Column('measures_property_keys', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('measurement_unit', sa.String(length=80), nullable=True),
    sa.Column('stated_uncertainty', sa.Float(), nullable=True),
    sa.Column('stated_uncertainty_unit', sa.String(length=80), nullable=True),
    sa.Column('calibration_status', sa.String(length=40), nullable=False),
    sa.Column('calibration_date', sa.Date(), nullable=True),
    sa.Column('calibration_due_date', sa.Date(), nullable=True),
    sa.Column('calibration_reference', sa.String(length=300), nullable=True),
    sa.Column('integration_kind', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'key', name='uq_instrument_scope_key')
    )
    op.create_index(op.f('ix_instruments_calibration_status'), 'instruments', ['calibration_status'], unique=False)
    op.create_index(op.f('ix_instruments_instrument_type'), 'instruments', ['instrument_type'], unique=False)
    op.create_index(op.f('ix_instruments_integration_kind'), 'instruments', ['integration_kind'], unique=False)
    op.create_index(op.f('ix_instruments_key'), 'instruments', ['key'], unique=False)
    op.create_index(op.f('ix_instruments_organisation_id'), 'instruments', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_instruments_status'), 'instruments', ['status'], unique=False)
    op.create_table('experiment_protocol_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('protocol_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('required_equipment', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sample_requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('preparation_steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('controlled_variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('independent_variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dependent_variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('measurement_procedure', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('calibration_requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('replicate_requirement', sa.Integer(), nullable=False),
    sa.Column('control_requirement', sa.String(length=300), nullable=True),
    sa.Column('protocol_checksum', sa.String(length=64), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['experiment_protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_id', 'version', name='uq_experiment_protocol_version')
    )
    op.create_index(op.f('ix_experiment_protocol_versions_protocol_id'), 'experiment_protocol_versions', ['protocol_id'], unique=False)
    op.create_index(op.f('ix_experiment_protocol_versions_superseded_by_id'), 'experiment_protocol_versions', ['superseded_by_id'], unique=False)
    op.create_index('ix_protocol_version_checksum', 'experiment_protocol_versions', ['protocol_checksum'], unique=False)
    op.create_table('samples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('sample_code', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('sample_kind', sa.String(length=40), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=True),
    sa.Column('hypothesis_id', sa.String(length=36), nullable=True),
    sa.Column('material_state_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('parent_sample_id', sa.String(length=36), nullable=True),
    sa.Column('batch_reference', sa.String(length=160), nullable=True),
    sa.Column('synthesis_reference', sa.Text(), nullable=True),
    sa.Column('processing_history_id', sa.String(length=36), nullable=True),
    sa.Column('geometry', sa.String(length=200), nullable=True),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mass_kg', sa.Float(), nullable=True),
    sa.Column('preparation_date', sa.Date(), nullable=True),
    sa.Column('prepared_by', sa.String(length=36), nullable=True),
    sa.Column('storage_conditions', sa.String(length=300), nullable=True),
    sa.Column('provenance_note', sa.Text(), nullable=True),
    sa.Column('provenance_complete', sa.Boolean(), nullable=False),
    sa.Column('provenance_gaps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['candidate_hypotheses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_state_id'], ['material_states.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['parent_sample_id'], ['samples.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prepared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['processing_history_id'], ['processing_histories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'sample_code', name='uq_sample_scope_code')
    )
    op.create_index('ix_sample_target', 'samples', ['material_id', 'hypothesis_id'], unique=False)
    op.create_index(op.f('ix_samples_batch_reference'), 'samples', ['batch_reference'], unique=False)
    op.create_index(op.f('ix_samples_candidate_id'), 'samples', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_samples_hypothesis_id'), 'samples', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_samples_material_id'), 'samples', ['material_id'], unique=False)
    op.create_index(op.f('ix_samples_material_state_id'), 'samples', ['material_state_id'], unique=False)
    op.create_index(op.f('ix_samples_organisation_id'), 'samples', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_samples_parent_sample_id'), 'samples', ['parent_sample_id'], unique=False)
    op.create_index(op.f('ix_samples_processing_history_id'), 'samples', ['processing_history_id'], unique=False)
    op.create_index(op.f('ix_samples_provenance_complete'), 'samples', ['provenance_complete'], unique=False)
    op.create_index(op.f('ix_samples_sample_code'), 'samples', ['sample_code'], unique=False)
    op.create_index(op.f('ix_samples_sample_kind'), 'samples', ['sample_kind'], unique=False)
    op.create_index(op.f('ix_samples_status'), 'samples', ['status'], unique=False)
    op.create_table('validation_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('target_kind', sa.String(length=30), nullable=False),
    sa.Column('target_scientific_id', sa.String(length=36), nullable=False),
    sa.Column('validation_state', sa.String(length=40), nullable=False),
    sa.Column('per_property_comparisons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('agreements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('disagreements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('conflicting_experiments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('experimentally_supported_requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('outstanding_requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('measurement_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('assessment_checksum', sa.String(length=64), nullable=False),
    sa.Column('superseded_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['replacement_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['material_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_assessments_organisation_id'), 'validation_assessments', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_validation_assessments_project_id'), 'validation_assessments', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_assessments_role_id'), 'validation_assessments', ['role_id'], unique=False)
    op.create_index(op.f('ix_validation_assessments_superseded_by_id'), 'validation_assessments', ['superseded_by_id'], unique=False)
    op.create_index(op.f('ix_validation_assessments_target_scientific_id'), 'validation_assessments', ['target_scientific_id'], unique=False)
    op.create_index(op.f('ix_validation_assessments_validation_state'), 'validation_assessments', ['validation_state'], unique=False)
    op.create_index('ix_validation_checksum', 'validation_assessments', ['assessment_checksum'], unique=False)
    op.create_index('ix_validation_scope', 'validation_assessments', ['role_id', 'target_scientific_id'], unique=False)
    op.create_table('experiment_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('requirement_id', sa.String(length=36), nullable=True),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('design_kind', sa.String(length=40), nullable=False),
    sa.Column('protocol_version_id', sa.String(length=36), nullable=False),
    sa.Column('factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('replicate_count', sa.Integer(), nullable=False),
    sa.Column('control_plan', sa.Text(), nullable=True),
    sa.Column('planned_run_count', sa.Integer(), nullable=False),
    sa.Column('design_checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['replacement_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['protocol_version_id'], ['experiment_protocol_versions.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['functional_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['material_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiment_plan_scope', 'experiment_plans', ['organisation_id', 'status'], unique=False)
    op.create_index(op.f('ix_experiment_plans_design_kind'), 'experiment_plans', ['design_kind'], unique=False)
    op.create_index(op.f('ix_experiment_plans_organisation_id'), 'experiment_plans', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_experiment_plans_project_id'), 'experiment_plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_experiment_plans_protocol_version_id'), 'experiment_plans', ['protocol_version_id'], unique=False)
    op.create_index(op.f('ix_experiment_plans_requirement_id'), 'experiment_plans', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_experiment_plans_role_id'), 'experiment_plans', ['role_id'], unique=False)
    op.create_index(op.f('ix_experiment_plans_status'), 'experiment_plans', ['status'], unique=False)
    op.create_table('experiment_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('requirement_id', sa.String(length=36), nullable=True),
    sa.Column('target_kind', sa.String(length=30), nullable=False),
    sa.Column('target_scientific_id', sa.String(length=36), nullable=False),
    sa.Column('property_definition_id', sa.String(length=36), nullable=True),
    sa.Column('unresolved_status', sa.String(length=40), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('current_evidence_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expected_evidence_type', sa.String(length=60), nullable=False),
    sa.Column('proposed_measurement', sa.Text(), nullable=False),
    sa.Column('suggested_protocol_id', sa.String(length=36), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('priority_methodology', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolved_by_run_id', sa.String(length=36), nullable=True),
    sa.Column('recommendation_checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['replacement_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_definition_id'], ['material_property_definitions.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['functional_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['material_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggested_protocol_id'], ['experiment_protocols.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiment_recommendation_scope', 'experiment_recommendations', ['role_id', 'target_scientific_id'], unique=False)
    op.create_index(op.f('ix_experiment_recommendations_organisation_id'), 'experiment_recommendations', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_experiment_recommendations_priority_score'), 'experiment_recommendations', ['priority_score'], unique=False)
    op.create_index(op.f('ix_experiment_recommendations_project_id'), 'experiment_recommendations', ['project_id'], unique=False)
    op.create_index(op.f('ix_experiment_recommendations_property_definition_id'), 'experiment_recommendations', ['property_definition_id'], unique=False)
    op.create_index(op.f('ix_experiment_recommendations_requirement_id'), 'experiment_recommendations', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_experiment_recommendations_resolved_by_run_id'), 'experiment_recommendations', ['resolved_by_run_id'], unique=False)
    op.create_index(op.f('ix_experiment_recommendations_role_id'), 'experiment_recommendations', ['role_id'], unique=False)
    op.create_index(op.f('ix_experiment_recommendations_status'), 'experiment_recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_experiment_recommendations_suggested_protocol_id'), 'experiment_recommendations', ['suggested_protocol_id'], unique=False)
    op.create_index(op.f('ix_experiment_recommendations_target_scientific_id'), 'experiment_recommendations', ['target_scientific_id'], unique=False)
    op.create_table('experiment_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('protocol_version_id', sa.String(length=36), nullable=False),
    sa.Column('protocol_checksum_at_run', sa.String(length=64), nullable=False),
    sa.Column('run_code', sa.String(length=160), nullable=False),
    sa.Column('sample_id', sa.String(length=36), nullable=True),
    sa.Column('instrument_id', sa.String(length=36), nullable=True),
    sa.Column('replicate_index', sa.Integer(), nullable=False),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('factor_levels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('deviation_notes', sa.Text(), nullable=True),
    sa.Column('invalidation_reason', sa.Text(), nullable=True),
    sa.Column('integration_kind', sa.String(length=60), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['experiment_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['protocol_version_id'], ['experiment_protocol_versions.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiment_run_plan_status', 'experiment_runs', ['plan_id', 'status'], unique=False)
    op.create_index('ix_experiment_run_sample', 'experiment_runs', ['sample_id'], unique=False)
    op.create_index(op.f('ix_experiment_runs_instrument_id'), 'experiment_runs', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_experiment_runs_is_control'), 'experiment_runs', ['is_control'], unique=False)
    op.create_index(op.f('ix_experiment_runs_organisation_id'), 'experiment_runs', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_experiment_runs_plan_id'), 'experiment_runs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_experiment_runs_protocol_version_id'), 'experiment_runs', ['protocol_version_id'], unique=False)
    op.create_index(op.f('ix_experiment_runs_run_code'), 'experiment_runs', ['run_code'], unique=False)
    op.create_index(op.f('ix_experiment_runs_sample_id'), 'experiment_runs', ['sample_id'], unique=False)
    op.create_index(op.f('ix_experiment_runs_status'), 'experiment_runs', ['status'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sample_id', sa.String(length=36), nullable=True),
    sa.Column('instrument_id', sa.String(length=36), nullable=True),
    sa.Column('property_definition_id', sa.String(length=36), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=80), nullable=True),
    sa.Column('canonical_value', sa.Float(), nullable=True),
    sa.Column('canonical_unit', sa.String(length=80), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('uncertainty_type', sa.String(length=60), nullable=True),
    sa.Column('method', sa.String(length=200), nullable=True),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('replicate_index', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality', sa.String(length=40), nullable=False),
    sa.Column('quality_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('processed_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('scientific_origin', sa.String(length=40), nullable=False),
    sa.Column('measurement_checksum', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['property_definition_id'], ['material_property_definitions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_measurement_property', 'measurements', ['property_definition_id', 'quality'], unique=False)
    op.create_index('ix_measurement_run', 'measurements', ['run_id'], unique=False)
    op.create_index(op.f('ix_measurements_instrument_id'), 'measurements', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_measurements_organisation_id'), 'measurements', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_measurements_processed_artifact_id'), 'measurements', ['processed_artifact_id'], unique=False)
    op.create_index(op.f('ix_measurements_property_definition_id'), 'measurements', ['property_definition_id'], unique=False)
    op.create_index(op.f('ix_measurements_quality'), 'measurements', ['quality'], unique=False)
    op.create_index(op.f('ix_measurements_raw_artifact_id'), 'measurements', ['raw_artifact_id'], unique=False)
    op.create_index(op.f('ix_measurements_run_id'), 'measurements', ['run_id'], unique=False)
    op.create_index(op.f('ix_measurements_sample_id'), 'measurements', ['sample_id'], unique=False)
    op.create_index(op.f('ix_measurements_scientific_origin'), 'measurements', ['scientific_origin'], unique=False)
    op.create_table('experiment_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('measurement_id', sa.String(length=36), nullable=True),
    sa.Column('content_role', sa.String(length=40), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('storage_reference', sa.String(length=200), nullable=False),
    sa.Column('content_checksum', sa.String(length=64), nullable=False),
    sa.Column('content_bytes', sa.Integer(), nullable=False),
    sa.Column('derived_from_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('processing_description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('inline_preview', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiment_artifact_run_role', 'experiment_artifacts', ['run_id', 'content_role'], unique=False)
    op.create_index(op.f('ix_experiment_artifacts_content_checksum'), 'experiment_artifacts', ['content_checksum'], unique=False)
    op.create_index(op.f('ix_experiment_artifacts_derived_from_artifact_id'), 'experiment_artifacts', ['derived_from_artifact_id'], unique=False)
    op.create_index(op.f('ix_experiment_artifacts_measurement_id'), 'experiment_artifacts', ['measurement_id'], unique=False)
    op.create_index(op.f('ix_experiment_artifacts_organisation_id'), 'experiment_artifacts', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_experiment_artifacts_run_id'), 'experiment_artifacts', ['run_id'], unique=False)


def downgrade():
    op.drop_table('validation_assessments')
    op.drop_table('experiment_recommendations')
    op.drop_table('experiment_artifacts')
    op.drop_table('measurements')
    op.drop_table('experiment_runs')
    op.drop_table('experiment_plans')
    op.drop_table('samples')
    op.drop_table('instruments')
    op.drop_table('experiment_protocol_versions')
    op.drop_table('experiment_protocols')
