"use client";
import { use, useState } from "react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { api, Evaluation, ProjectDetail, Specification } from "@/lib/api";
import { StatusBadge } from "@/components/StatusBadge";

const tabs=["Overview","Requirements","Baseline","Candidates","Comparison","Evidence","Activity"];
export default function ProjectPage({params}:{params:Promise<{id:string}>}){
  const {id}=use(params); const [tab,setTab]=useState("Overview");
  const project=useQuery({queryKey:["project",id],queryFn:()=>api<ProjectDetail>(`/replacement-projects/${id}`)});
  const spec=useQuery({queryKey:["spec",id],queryFn:()=>api<Specification>(`/replacement-projects/${id}/specification`)});
  const evals=useQuery({queryKey:["comparison",id],queryFn:()=>api<Evaluation[]>(`/replacement-projects/${id}/comparison`)});
  if(project.isLoading) return <div className="empty">Loading project…</div>;
  if(project.error||!project.data) return <div className="empty">Project unavailable: {(project.error as Error)?.message}</div>;
  const p=project.data;
  return <>
    <div className="topline"><div><div className="eyebrow">Replacement study</div><h1>{p.name}</h1><div className="muted">Baseline: <Link href={`/materials/${p.baseline_material.id}`}>{p.baseline_material.display_name}</Link></div></div><div style={{display:"flex",gap:8,alignItems:"center"}}><Link className="btn" href={`/projects/${id}/virtual-lab`}>Virtual Experiment Lab</Link><Link className="btn btn-secondary" href={`/projects/${id}/prediction-lab`}>Prediction Lab</Link><Link className="btn btn-secondary" href={`/projects/${id}/candidate-lab`}>Candidate Lab</Link><Link className="btn btn-secondary" href={`/projects/${id}/industrial`}>Industrial Viability</Link><Link className="btn btn-secondary" href={`/projects/${id}/validation`}>Scientific Validation</Link><Link className="btn" href={`/projects/${id}/replacement`}>Replacement Mission Control</Link><span className="badge">{p.status}</span></div></div>
    <div className="tabs">{tabs.map(t=><button key={t} className={`tab ${tab===t?"active":""}`} onClick={()=>setTab(t)}>{t}</button>)}</div>
    {tab==="Overview"&&<div className="grid grid-2"><div className="card card-pad"><h2>Scientific problem</h2><p className="muted">{p.description}</p><div><span className="kicker">Replacement reasons</span><p>{p.replacement_reasons.join(" · ")}</p></div><div><span className="kicker">Specification checksum</span><p><code>{spec.data?.checksum ?? "…"}</code></p></div></div><div className="card card-pad"><h2>Scope guard</h2><p className="muted">Phase 5 adds bounded, uncertainty-aware virtual experiment campaigns and Pareto trade-off exploration. Virtual evaluations remain model-based and separate from evidence; physics simulation, physical validation, patent search, and laboratory automation remain deliberately unavailable.</p></div></div>}
    {tab==="Requirements"&&<div className="grid"><div className="card"><div className="card-pad"><h2>Constraints</h2></div><div className="table-wrap"><table><thead><tr><th>Strength</th><th>Property</th><th>Comparator</th><th>Target</th><th>Weight</th></tr></thead><tbody>{p.constraints.map(c=><tr key={c.id}><td><span className="badge">{c.hard_or_soft}</span></td><td>{c.property_key}</td><td>{c.comparator}</td><td>{c.target_boolean!==undefined&&c.target_boolean!==null?String(c.target_boolean):`${c.target_value ?? ""} ${c.target_unit ?? ""}`}</td><td>{c.weight}</td></tr>)}</tbody></table></div></div><div className="card"><div className="card-pad"><h2>Objectives</h2></div><div className="table-wrap"><table><thead><tr><th>Priority</th><th>Property</th><th>Direction</th><th>Weight</th></tr></thead><tbody>{p.objectives.map(o=><tr key={o.id}><td>{o.priority}</td><td>{o.property_key}</td><td>{o.direction}</td><td>{o.weight}</td></tr>)}</tbody></table></div></div></div>}
    {tab==="Baseline"&&<div className="card card-pad"><h2>{p.baseline_material.display_name}</h2><p className="muted">{p.baseline_material.description}</p><Link className="btn btn-secondary" href={`/materials/${p.baseline_material.id}`}>Open material passport</Link></div>}
    {tab==="Candidates"&&<div className="card"><div className="card-pad"><h2>Attached candidates</h2><p className="muted">Known materials and hypotheses remain distinct. Hypotheses never inherit baseline properties; use Candidate Lab and Prediction Lab for their lineage and model-backed estimates.</p></div><div className="table-wrap"><table><thead><tr><th>Candidate</th><th>Kind</th><th>Source</th><th>Status</th><th>Evidence posture</th></tr></thead><tbody>{p.candidates.map(c=>{const ev=evals.data?.find(e=>e.candidate_id===c.id);return <tr key={c.id}><td>{c.candidate_kind==="hypothesis"&&c.hypothesis_id?<Link href={`/candidate-hypotheses/${c.hypothesis_id}`}><strong>Hypothesis {c.hypothesis_id.slice(0,8)}…</strong></Link>:c.material?<Link href={`/materials/${c.material.id}`}><strong>{c.material.display_name}</strong></Link>:"—"}</td><td><span className="badge">{c.candidate_kind??"known_material"}</span></td><td>{c.candidate_source}</td><td>{c.status}</td><td>{ev?`${Math.round(ev.completeness*100)}% constraint evidence complete`:"…"}</td></tr>})}</tbody></table></div></div>}
    {tab==="Comparison"&&<div className="grid">{evals.data?.map(e=><div className="card" key={e.candidate_id}><div className="card-pad" style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h2>{e.material_name}</h2><div className="muted">Hard pass {e.hard_passed} · hard fail {e.hard_failed} · unknown {e.unknown}</div></div><span className="badge">{Math.round(e.completeness*100)}% complete</span></div><div className="table-wrap"><table><thead><tr><th>Requirement</th><th>Observed</th><th>Status</th><th>Selected evidence</th><th>Applicability</th><th>Conflict</th><th>Unknown reason</th></tr></thead><tbody>{e.constraints.map((c,i)=><tr key={`${c.property_key}-${i}`}><td>{c.property_key}</td><td>{c.observed_value===undefined||c.observed_value===null?"—":`${c.observed_value} ${c.observed_unit??""}`}{c.canonical_value!==undefined&&c.canonical_value!==null&&<div className="muted">canonical {Number(c.canonical_value).toFixed(3)} {c.canonical_unit??""}</div>}</td><td><StatusBadge status={c.status}/></td><td>{c.selected_observation_id?<><Link href={`/observations/${c.selected_observation_id}`}>Open observation</Link><div className="muted">{c.alternatives_count} alternative(s)</div></>:"—"}</td><td>{c.applicability?<span className="badge">{c.applicability}</span>:"—"}<div className="muted">{c.selection_rationale?.[0]??""}</div></td><td>{c.conflict?<span className="badge fail">Conflict</span>:<span className="badge pass">Clear</span>}</td><td className="muted">{c.unknown_reason??"—"}</td></tr>)}</tbody></table></div></div>)}</div>}
    {tab==="Evidence"&&<div className="card card-pad"><h2>Evidence-first evaluation</h2><p className="muted">Each evaluated scalar carries the selected observation, applicability, evidence provenance, alternatives count, and conflict state. Open a material passport for evidence titles, methods, conditions, uncertainty, and source references.</p><div className="notice">Seed evidence explicitly states that values are synthetic demonstration fixtures and not experimental claims.</div></div>}
    {tab==="Activity"&&<div className="card card-pad"><h2>Activity</h2><div className="empty">Phase 5 stores evidence provenance, generation lineage, prediction model/version provenance, virtual-campaign decisions, and reproducibility records but does not pretend a full enterprise audit trail exists. Audit-event infrastructure belongs to the enterprise phase.</div></div>}
    <div className="card card-pad" style={{marginTop:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h2>Replacement specification</h2><div className="muted">Authoritative server-compiled JSON · semantic SHA-256 checksum</div></div><button className="btn btn-secondary" onClick={()=>navigator.clipboard.writeText(JSON.stringify(spec.data?.canonical_payload??{},null,2))}>Copy JSON</button></div><pre className="json" style={{marginTop:14}}>{JSON.stringify(spec.data?.canonical_payload??{},null,2)}</pre></div>
  </>;
}
